# Introduction
The objective of this introductory notebook is to present Numpy and some of its main functionalities. 

**Note:** Before doing this notebook you should know a bit of Python. If you would like to refresh your memory, you can take a look at the <a href="https://docs.python.org/3/tutorial/">**Python tutorial**</a>.

#### Required libraries
* <a href = "https://numpy.org/"><code>Numpy</code></a> 

#### Table of contents
<ol>
    <li><a href="#what_is_numpy">What is Numpy?</a></li>
    <li><a href="#why_use_numpy">Why use Numpy?</a></li>
    <li><a href="#arrays">Arrays</a></li>
    <li><a href="#data_types">Data types</a></li>
    <li><a href="#array_indexing">Array indexing</a><br>
        5.1 <a href="#slicing">Slicing</a><br>
        5.2 <a href="#integer_indexing">Integer indexing</a><br>
        5.3 <a href="#boolean_indexing">Boolean indexing</a>
    </li>
    <li><a href="#data_types">Array math</a></li>
    <li><a href="#broadcasting">Broadcasting</a></li>
</ol>

***

<h2 id="what_is_numpy">1 - What is Numpy?</h2>

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. Each array is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. Unlike a Python list, numpy arrays are made up of <a href="https://numpy.org/devdocs/user/basics.types.html">**primitive data types**</a>, which provides considerable memory and speed advantages.

Numpy has many similarities with MATLAB, if you are familiar with it, you might find <a href="https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html">**this tutorial**</a> useful to get started with Numpy.

Also, check out the <a href="http://docs.scipy.org/doc/numpy/reference/">**Numpy reference**</a> to find out much more about Numpy.

<h2 id="why_use_numpy">2 - Why use Numpy?</h2>

* **Size**. Numpy data structures take up less space.
* **Performance**. It uses <a href="https://en.wikipedia.org/wiki/SIMD">**SIMD**</a> to parallelize operations that are programmed in C, resulting in better performance.
* **Functionality**. NumPy has optimized functions such as linear algebra operations built in. It is also the base data representation for scientific computing in Python.

#### Performance example

In [1]:
import numpy as np
import time
size = 1000000  #Size of array 
L1 = range(size)
L2 = range(size)

# declare two arrays
a1 = np.arange(size)  
a2 = np.arange(size)

## list
start = time.time()
result = [(x+y) for x,y in zip(L1 , L2)]
print("python list took :" ,(time.time()-start))

## numpy array
start = time.time()
result = a1 + a2
print("numpy array took :" ,(time.time() - start))

python list took : 0.2638368606567383
numpy array took : 0.022986888885498047


<h2 id="arrays">3 - Arrays</h2>
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

* **Rank**. The rank of an array is simply the number of axes (or dimensions) it has. 
* **Shape**. The shape of an array specifies the length of the array in each dimension. It is usually represented as a tuple. For a given array, the number of elements in the shape tuple will be equal to the rank of the array. Lets see some examples.

#### 1-dimensional

![](images/rank1.png)

A 1 dimensional array (rank 1). It has 5 elements so its shape is the tuple <code>(5,)</code>

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### 2-dimensional

![](images/rank2.png)

A 2 dimensional array (rank 2). It has 3 rows and 5 columns so its shape is the tuple <code>(3,5)</code>. By convention, we take the matrix shape to be rows first, then columns.

In [3]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 3-dimensional

![](images/rank3.png)

The rank 3 array has 4 planes, each containing 3 rows and 5 columns, so its shapes is <code>(4, 3, 5)</code>. By convention, we take the matrix shape to be planes first, then rows, then columns.

In [4]:
np.zeros((4,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [5]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [6]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

(2, 3)
1 2 4


In [7]:
c = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])   # Create a rank 3 array
print(c.shape)                                         # Prints "(2, 2, 3)"
print(c[0,1,2])

(2, 2, 3)
6


Numpy also provides many functions to create arrays:

In [8]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

[[0. 0.]
 [0. 0.]]


In [9]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

[[1. 1.]]


In [10]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

[[7 7]
 [7 7]]


In [11]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[1. 0.]
 [0. 1.]]


In [15]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0.82351481 0.06570482]
 [0.36691239 0.87078411]]


<h2 id="data_types">4 - Data types</h2>

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [16]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int32
float64
int64


You can read all about numpy datatypes <a href="http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html">**in the documentation**</a>.

#### Comparison with Python list

Lets show the size flexibility of Numpy in comparison with a Python's list of <code>int</code> values:

In [17]:
from sys import getsizeof
import numpy as np

# Numpy has a constant memory usage of 96 bytes
print(getsizeof(np.arange(1000, dtype=np.int8)))
print(getsizeof(np.arange(1000, dtype=np.int16)))
print(getsizeof(np.arange(1000, dtype=np.int32)))
print(getsizeof(np.arange(1000, dtype=np.int64)))
print(getsizeof(np.arange(1000, dtype=np.float64)))

# Python 
print(getsizeof(list(range(0,1000))))

1096
2096
4096
8096
8096
8056


<h2 id="array_indexing">5 - Array indexing</h2>

Numpy offers several ways to index into arrays:

* **Slicing**
* **Integer indexing**
* **Boolean indexing** (also known as conditional indexing)

<h3 id="slicing">5.1 - Slicing</h3>

Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [42]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 
# 2 rows and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[0:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [21]:
# A slice of an array is a view into the same data, so modifying it 
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a)

2
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<h3 id="integer_indexing">5.2 - Integer indexing</h3>

**Note:** It results in an array of lower rank than the original array.

In [22]:
a = np.array([[1,2], [3, 4], [5, 6]])

print(a[1])      # [3,4]
print(a[2,0])    # 5

[3 4]
5


We can also mix integer indexing with slice indexing. However, doing so will also yield an array of lower rank than the original array. 

In [23]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


<h3 id="boolean_indexing">5.3 - Boolean indexing</h3>

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. 

**Note:** It results in an array of lower rank than the original array.

In [24]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

# We can manually create the boolean index (i.e., it comes from an external method)
manual_idx = np.array([[False, False],[ True,  True],[ True,  True]])
print(a[manual_idx])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should <a href="http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html">**read the documentation**</a>.

<h2 id="array_math">6 - Array math</h2>

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [25]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [26]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [27]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [28]:
# Elementwise division; both produce the array
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [29]:
# Elementwise square root; produces the array
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [30]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; 
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; 
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; 
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is <code>sum</code>.

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints 
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1))  # Compute sum of each row

You can find the full list of mathematical functions provided by numpy <a href="http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html">**in the documentation**</a>.

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the <code>T</code> attribute of an array object:

In [ ]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    
print(x.T)  

Note that taking the transpose of a rank 1 array does nothing:

In [ ]:
v = np.array([1,2,3])
print(v)   
print(v.T)  

<h2 id="broadcasting">7 - Broadcasting</h2>

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [31]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix <code>x</code> is very large, computing an explicit loop in Python could be slow. Note that adding the vector <code>v</code> to each row of the matrix <code>x</code> is equivalent to forming a matrix <code>vv</code> by stacking multiple copies of <code>v</code> vertically, then performing elementwise summation of <code>x</code> and <code>v</code>. We could implement this approach like this:

In [32]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation **without actually creating multiple copies of** <code>v</code>:

In [33]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line <code>y = x + v</code> works even though <code>x</code> has shape <code>(4, 3)</code> and <code>v</code> has shape <code>(3,)</code> due to broadcasting; this line works as if <code>v</code> actually had shape <code>(4, 3)</code>, where each row was a copy of <code>v</code>, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation <a href="http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html">**from the documentation**</a> or <a href="http://wiki.scipy.org/EricsBroadcastingDoc">**this explanation**</a>.

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions <a href="http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs">**in the documentation**</a>.

Here are some applications of broadcasting:

#### Add a vector to each row of a matrix

In [34]:
x = np.array([[1,2,3], [4,5,6]])   # x has shape (2, 3)
v = np.array([1, 0, 1])            # v has shape (3,)

# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 2 4]
#  [5 5 7]]
print(x + v)

[[2 2 4]
 [5 5 7]]


#### Compute outer product of vectors

In [35]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


#### Add a vector to each column of a matrix

In [36]:
x = np.array([[1,2,3], [4,5,6]])  # x has shape (2, 3)
w = np.array([4,5])               # w has shape (2,)

# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)

# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]


#### Multiply a matrix by a constant

In [ ]:
x = np.array([[1,2,3], [4,5,6]])

# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

## References

#### Links
1. <a href="https://cs231n.github.io/python-numpy-tutorial/">CS231n (Standford): Convolutional Neural Networks for Visual Recognition. Python Numpy Tutorial.</a>